import CourseRequest from "@/src/components/teacher/CourseRequest";
import React from "react";

const data = [
  {
    courseCode: 12345,
    section: 801,
    studentList: [
      {
        id: "1",
        studentId: 640210011,
        name: "Paul William",
        faculty: "Business and Economic",
        major: "Business Administration",
        status: "Approved",
        grade: "-",
      },
      {
        id: "2",
        studentId: 640210012,
        name: "Alice Johnson",
        faculty: "Science",
        major: "Biology",
        status: "Pending",
        grade: "-",
      },
      {
        id: "3",
        studentId: 640210013,
        name: "Bob Smith",
        faculty: "Engineering",
        major: "Computer Engineering",
        status: "Approved",
        grade: "3.50",
      },
      {
        id: "4",
        studentId: 640210014,
        name: "Charlie Brown",
        faculty: "Arts",
        major: "Literature",
        status: "Rejected",
        grade: "-",
      },
      {
        id: "5",
        studentId: 640210015,
        name: "David Wilson",
        faculty: "Business and Economic",
        major: "Economics",
        status: "Approved",
        grade: "3.70",
      },
    ],
  },
  {
    courseCode: 12345,
    section: 802,
    studentList: [
      {
        id: "1",
        studentId: 640210011,
        name: "Paul William",
        faculty: "Business and Economic",
        major: "Business Administration",
        status: "Approved",
        grade: "-",
      },
      {
        id: "2",
        studentId: 640210012,
        name: "Alice Johnson",
        faculty: "Science",
        major: "Biology",
        status: "Pending",
        grade: "-",
      },
      {
        id: "3",
        studentId: 640210013,
        name: "Bob Smith",
        faculty: "Engineering",
        major: "Computer Engineering",
        status: "Approved",
        grade: "3.50",
      },
      {
        id: "4",
        studentId: 640210014,
        name: "Charlie Brown",
        faculty: "Arts",
        major: "Literature",
        status: "Rejected",
        grade: "-",
      },
      {
        id: "5",
        studentId: 640210015,
        name: "David Wilson",
        faculty: "Business and Economic",
        major: "Economics",
        status: "Approved",
        grade: "3.70",
      },
    ],
  },
  {
    courseCode: 12345,
    section: 803,
    studentList: [
      {
        id: "1",
        studentId: 640210011,
        name: "Paul William",
        faculty: "Business and Economic",
        major: "Business Administration",
        status: "Approved",
        grade: "-",
      },
      {
        id: "2",
        studentId: 640210012,
        name: "Alice Johnson",
        faculty: "Science",
        major: "Biology",
        status: "Pending",
        grade: "-",
      },
      {
        id: "3",
        studentId: 640210013,
        name: "Bob Smith",
        faculty: "Engineering",
        major: "Computer Engineering",
        status: "Approved",
        grade: "3.50",
      },
      {
        id: "4",
        studentId: 640210014,
        name: "Charlie Brown",
        faculty: "Arts",
        major: "Literature",
        status: "Rejected",
        grade: "-",
      },
      {
        id: "5",
        studentId: 640210015,
        name: "David Wilson",
        faculty: "Business and Economic",
        major: "Economics",
        status: "Approved",
        grade: "3.70",
      },
    ],
  },
  {
    courseCode: 12346,
    section: 802,
    studentList: [
      {
        id: "1",
        studentId: 640210011,
        name: "Paul William",
        faculty: "Business and Economic",
        major: "Business Administration",
        status: "Approved",
        grade: "-",
      },
      {
        id: "2",
        studentId: 640210012,
        name: "Alice Johnson",
        faculty: "Science",
        major: "Biology",
        status: "Pending",
        grade: "-",
      },
      {
        id: "3",
        studentId: 640210013,
        name: "Bob Smith",
        faculty: "Engineering",
        major: "Computer Engineering",
        status: "Approved",
        grade: "3.50",
      },
      {
        id: "4",
        studentId: 640210014,
        name: "Charlie Brown",
        faculty: "Arts",
        major: "Literature",
        status: "Rejected",
        grade: "-",
      },
      {
        id: "5",
        studentId: 640210015,
        name: "David Wilson",
        faculty: "Business and Economic",
        major: "Economics",
        status: "Approved",
        grade: "3.70",
      },
    ],
  },
  {
    courseCode: 12347,
    section: 803,
    studentList: [
      {
        id: "1",
        studentId: 640210011,
        name: "Paul William",
        faculty: "Business and Economic",
        major: "Business Administration",
        status: "Approved",
        grade: "-",
      },
      {
        id: "2",
        studentId: 640210012,
        name: "Alice Johnson",
        faculty: "Science",
        major: "Biology",
        status: "Pending",
        grade: "-",
      },
      {
        id: "3",
        studentId: 640210013,
        name: "Bob Smith",
        faculty: "Engineering",
        major: "Computer Engineering",
        status: "Approved",
        grade: "3.50",
      },
      {
        id: "4",
        studentId: 640210014,
        name: "Charlie Brown",
        faculty: "Arts",
        major: "Literature",
        status: "Rejected",
        grade: "-",
      },
      {
        id: "5",
        studentId: 640210015,
        name: "David Wilson",
        faculty: "Business and Economic",
        major: "Economics",
        status: "Approved",
        grade: "3.70",
      },
    ],
  },
];

const TeacherRequestedCourse = () => {
  return (
    <div>
      <CourseRequest />
    </div>
  );
};

export default TeacherRequestedCourse;
